### ISSUE TITLE
Why won't you update to latest openvpn version?

### ISSUE THREAD

**Issue by UgVaDevLabs** [schwabe/openvpn#10]
Current latest openvpn version is 2.4.6 but this repository is still using 2.4.5. I noticed that there was a branch, tag and a release for 2.4.6 version https://github.com/schwabe/openvpn/releases/tag/v2.4.6 however that branch was never merged into master. Can you explain why?

**Comment by schwabe** [comment]
You are confusing tags with actual version being used. And for master vs release/2.4 branch please see the upstream documentation:

https://community.openvpn.net/openvpn/wiki/CodeRepositories

my app follows the master branch of OpenVPN.

Also see the icsopenvpn tags for the actual code used in the app: https://github.com/schwabe/openvpn/releases

**Comment by UgVaDevLabs** [comment]
Thank you for the information. Do you know if https://github.com/OpenVPN/openvpn repository (your app as well) is up to date and using the latest 2.4.6 version?
