### ISSUE TITLE
Unable to count traffic using bytecount

### ISSUE THREAD

**Issue by gznail** [schwabe/openvpn#17]

**Comment by gznail** [comment]
git clone -b dco https://github.com/ordex/openvpn.git

**Comment by schwabe** [comment]
This not the right place to report issues in openvpn.

**Comment by gznail** [comment]
There is also a problem with this version. Damn, is the feedback so exclusive?

**Comment by gznail** [comment]
Has anyone else tested you out?

**Comment by schwabe** [comment]
@gznail: This is my private repository that contains fork of OpenVPN. It is just not the right place to report bugs and issues. And if you look at the README.dco.md, there is already under known issues:

`- No per client statistics. Only total statistics available on the interface.  `

No need to report something we already know
