### ISSUE TITLE
Build wih min sdk version higher than 23

### ISSUE THREAD

**Issue by SM2A** [schwabe/openvpn#18]
https://github.com/schwabe/openvpn/blob/ee0100b4a0ac49e7c504bc242f94678151cb6771/src/compat/compat.h#L46

Hi
I wanted to build this project in an android app with minimum sdk version higher than 23. It happens to be a function with exact `basename` in NDK `string.h`

```c
#if defined(__USE_GNU) && !defined(basename)
/*
 * glibc has a basename in <string.h> that's different to the POSIX one in <libgen.h>.
 * It doesn't modify its argument, and in C++ it's const-correct.
 */
#if defined(__cplusplus)
extern "C++" char* basename(char* _Nonnull) __RENAME(__gnu_basename);
extern "C++" const char* basename(const char* _Nonnull) __RENAME(__gnu_basename);
#else

#if __ANDROID_API__ >= 23
char* basename(const char* _Nonnull) __RENAME(__gnu_basename) __INTRODUCED_IN(23);
#endif /* __ANDROID_API__ >= 23 */

#endif
#endif
```

What are the usages of this method other than this:
```c
void
init_options_dev(struct options *options)
{
    if (!options->dev && options->dev_node)
    {
        char *dev_node = string_alloc(options->dev_node, NULL); /* POSIX basename() implementations may modify its arguments */
        options->dev = compat_basename(dev_node);
    }
}
```
I want to change the name of this function to something else. Is this a good idea?

**Comment by schwabe** [comment]
No. You shuold change the the configuration header to indicate that OpenVPN should not use the compat function instead. The compat_* function are only used when the OS is not providing them. Normally autoconf detects this but the Android build uses a manual maintained configuration instead.

**Comment by SM2A** [comment]
I just want to make sure that I get it right.
I have to do something like this? https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/cpp/openvpn-config/config.h
Thanks

**Comment by schwabe** [comment]
yes that is the place.
