### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by mesterj** [schwabe/openvpn#3]
Hello

I have 10.1 col Full HD lenovo tablet. Maybe the needed icon size is missing from apk. I think it because the OpenVPN icon is the default green droid.

**Comment by schwabe** [comment]
Are you using the official APK from the play store? I never have seen this behaviour on any device.

**Comment by schwabe** [comment]
Also completely wrong repo

**Comment by mesterj** [comment]
Yes. I am using play store.
