### ISSUE TITLE
What's the difference between this repository and  Official edition ? 

### ISSUE THREAD

**Issue by LiTianjue** [schwabe/openvpn#4]
there are any android porting  tutorials for openvpn like your openssl  repository （platform_external_openssl）

i need to port a special edition of openvpn for andorid and use ics-openvpn app for testing  ，so i'd like to compile it as your pattern to replace "libopenvpn.so"

so , may i get some guidance here ?

**Comment by LiTianjue** [comment]
or where can i get " dual stack client patches" which  talk about in  https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt

**Comment by schwabe** [comment]
there is the doc/README.txt that tells you how to compile the project. Further documentation of compiling opennvpn on Android is only available in the make files of the project.

The README is a bit outdated. The dual stack patches are included in OpenVPN master.

**Comment by LiTianjue** [comment]
you mean i can  use source code from  OpenVPN master  directly ? how about breakpad.cpp ?Is this necessary ?  Do i need do this part manually

**Comment by schwabe** [comment]
@LiTianjue results may vary. Just look at the extra commits in my openvpn repo to get an idea what the difference is. You need at least the patches for building on Android. 

Breakpad is just google breakpad support, you don't need that.

**Comment by LiTianjue** [comment]
Thanks for your reply
