### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by zero77** [schwabe/openvpn#5]
Can you add support for automatic updates, so you don't have to reinstall it every time there's a new update available.

**Comment by schwabe** [comment]
Automatic updates are supported by play store/amazon store/F-Droid.

**Comment by zero77** [comment]
Is automatic updates supported in Windows

**Comment by schwabe** [comment]
wrong issue tracker. I am dealing only with Android.

**Comment by zero77** [comment]
o ok, sorry
