### ISSUE TITLE
[Request] Start At System Start Up

### ISSUE THREAD

**Issue by zero77** [schwabe/openvpn#6]
Can you add an option to start at system start up, both the app and connecting to a vpn.
Thanks

**Comment by schwabe** [comment]
- Wrong repository
- Already implemented

**Comment by zero77** [comment]
Sorry, which repository should I use and is it enabled by default.

**Comment by schwabe** [comment]
This is not a  repository for the Android app. ics-openvpn is that repo. And it is under General settings.
