### ISSUE TITLE
/usr/include/linux/rtnetlink.h:487: error: expected specifier-qualifier-list before '__u64'

### ISSUE THREAD

**Issue by ledav-net** [schwabe/openvpn#9]
Hi,

I've an issue trying to compile the official release "openvpn v2.4.6":

gcc -DHAVE_CONFIG_H -I. -I../.. -I../../include  -I../../include -I../../src/compat   -I/usr/kerberos/include      -DPLUGIN_LIBDIR=\"/usr/local/lib/openvpn/plugins\"  -Wall -Wno-unused-parameter -Wno-unused-function -g -O2 -std=c99 -MT route.o -MD -MP -MF .deps/route.Tpo -c -o route.o route.c
In file included from route.c:48:
/usr/include/linux/rtnetlink.h:487: error: expected specifier-qualifier-list before '__u64'
/usr/include/linux/rtnetlink.h:656: error: expected specifier-qualifier-list before '__u64'
make[3]: *** [route.o] Error 1

It can be fixed by removing the "-std=c99" parameter... However, there is certainly a better way to do that... Maybe there is already a patch to fix this ?

I'm running a CentOS 5 with the latest updates.

Thanks in advance for your help & return.

Regards,
David.

**Comment by schwabe** [comment]
This is the wrong repo for this kind of reports
